### PR TITLE
Remove the exception squares in front of the log & fix issue #207 & Nums detection

### PR DESCRIPTION
**Pull request by GuangChen2333**
### Fix
1. Fix Issue #207 -> Added an `input()` function internally

2. Remove the `{level.icon}` in logger to remove the exception squares in front of the log

(I don't know what the role of `{level.icon}` is)

### New
1. Add non-pure digital detection

### CODE REVIEW

**Comment by GuangChen2333** [comment]
知道方块是什么了 为什么会有emoji在log里面啊🤔

**Comment by MBRjun** [comment]
中国人给中国人交英文pr和issue.jpg  
（挺草的，这事我也在干

**Review by MBRjun — APPROVED** [review]

**Comment by GuangChen2333** [comment]
233333333333

**Review by GuangChen2333 — COMMENTED** [review]
1

**Comment by GuangChen2333** [comment]
(因为某些原因数据寄了远程库也寄了故重开pr并撤回提交[5fba2d7](https://github.com/OpenEthan/SMSBoom/pull/213/commits/5fba2d7d1ab826ecd13b48ec2134e510b932ea92)

**Comment by GuangChen2333** [comment]
见 Pull Requests #216

**Comment by OpenEthan** [comment]
Hello, I am very grateful for your contribution to the project. `{level.ico}` is the emoji icon parameter of the lourger log third party module, mainly used to display the log level icon, it may not take effect in some command lines, error characters appear and should be removed.

For the command line parameters, my mistake, thx! 😄

**Pull request closed without merging**
